ccTLDs = {
	"ac":"Ascension Island (United Kingdom)",
	"ad":"Andorra",
	"ae":"United Arab Emirates",
	"af":"Afghanistan",
	"ag":"Antigua and Barbuda",
	"ai":"Anguilla (United Kingdom)",
	"al":"Albania",
	"am":"Armenia",
	"ao":"Angola",
	"aq":"Antarctica",
	"ar":"Argentina",
	"as":"American Samoa (United States)",
	"at":"Austria",
	"au":"Australia",
	"aw":"Aruba (Kingdom of the Netherlands)",
	"ax":"Åland (Finland)",
	"az":"Azerbaijan",
	"ba":"Bosnia and Herzegovina",
	"bb":"Barbados",
	"bd":"Bangladesh",
	"be":"Belgium",
	"bf":"Burkina Faso",
	"bg":"Bulgaria",
	"bh":"Bahrain",
	"bi":"Burundi",
	"bj":"Benin",
	"bm":"Bermuda (United Kingdom)",
	"bn":"Brunei",
	"bo":"Bolivia",
	"bq":"Caribbean Netherlands (Bonaire,  Saba, and  Sint Eustatius)",
	"br":"Brazil",
	"bs":"Bahamas",
	"bt":"Bhutan",
	"bw":"Botswana",
	"by":"Belarus",
	"bz":"Belize",
	"ca":"Canada",
	"cc":"Cocos (Keeling) Islands",
	"cd":"Democratic Republic of the Congo",
	"cf":"Central African Republic",
	"cg":"Republic of the Congo",
	"ch":"Switzerland",
	"ci":"Ivory Coast",
	"ck":"Cook Islands",
	"cl":"Chile",
	"cm":"Cameroon",
	"cn":"People's Republic of China",
	"co":"Colombia",
	"cr":"Costa Rica",
	"cu":"Cuba",
	"cv":"Cape Verde",
	"cw":"Curaçao (Kingdom of the Netherlands)",
	"cx":"Christmas Island",
	"cy":"Cyprus",
	"cz":"Czech Republic",
	"de":"Germany",
	"dj":"Djibouti",
	"dk":"Denmark",
	"dm":"Dominica",
	"do":"Dominican Republic",
	"dz":"Algeria",
	"ec":"Ecuador",
	"ee":"Estonia",
	"eg":"Egypt",
	"eh":"Western Sahara",
	"er":"Eritrea",
	"es":"Spain",
	"et":"Ethiopia",
	"eu":"European Union",
	"fi":"Finland",
	"fj":"Fiji",
	"fk":"Falkland Islands (United Kingdom)",
	"fm":"Federated States of Micronesia",
	"fo":"Faroe Islands (Kingdom of Denmark)",
	"fr":"France",
	"ga":"Gabon",
	"gd":"Grenada",
	"ge":"Georgia",
	"gf":"French Guiana (France)",
	"gg":"Guernsey",
	"gh":"Ghana",
	"gi":"Gibraltar (United Kingdom)",
	"gl":"Greenland (Kingdom of Denmark)",
	"gm":"The Gambia",
	"gn":"Guinea",
	"gp":"Guadeloupe (France)",
	"gq":"Equatorial Guinea",
	"gr":"Greece",
	"gs":"South Georgia and the South Sandwich Islands (United Kingdom)",
	"gt":"Guatemala",
	"gu":"Guam (United States)",
	"gw":"Guinea-Bissau",
	"gy":"Guyana",
	"hk":"Hong Kong",
	"hm":"Heard Island and McDonald Islands",
	"hn":"Honduras",
	"hr":"Croatia",
	"ht":"Haiti",
	"hu":"Hungary",
	"id":"Indonesia",
	"ie":"Ireland",
	"il":"Israel",
	"im":"Isle of Man",
	"in":"India",
	"io":"British Indian Ocean Territory (United Kingdom)",
	"iq":"Iraq",
	"ir":"Iran",
	"is":"Iceland",
	"it":"Italy",
	"je":"Jersey",
	"jm":"Jamaica",
	"jo":"Jordan",
	"jp":"Japan",
	"ke":"Kenya",
	"kg":"Kyrgyzstan",
	"kh":"Cambodia",
	"ki":"Kiribati",
	"km":"Comoros",
	"kn":"Saint Kitts and Nevis",
	"kp":"North Korea",
	"kr":"South Korea",
	"kw":"Kuwait",
	"ky":"Cayman Islands (United Kingdom)",
	"kz":"Kazakhstan",
	"la":"Laos",
	"lb":"Lebanon",
	"lc":"Saint Lucia",
	"li":"Liechtenstein",
	"lk":"Sri Lanka",
	"lr":"Liberia",
	"ls":"Lesotho",
	"lt":"Lithuania",
	"lu":"Luxembourg",
	"lv":"Latvia",
	"ly":"Libya",
	"ma":"Morocco",
	"mc":"Monaco",
	"md":"Moldova",
	"me":"Montenegro",
	"mg":"Madagascar",
	"mh":"Marshall Islands",
	"mk":"North Macedonia",
	"ml":"Mali",
	"mm":"Myanmar",
	"mn":"Mongolia",
	"mo":"Macau",
	"mp":"Northern Mariana Islands (United States)",
	"mq":"Martinique (France)",
	"mr":"Mauritania",
	"ms":"Montserrat (United Kingdom)",
	"mt":"Malta",
	"mu":"Mauritius",
	"mv":"Maldives",
	"mw":"Malawi",
	"mx":"Mexico",
	"my":"Malaysia",
	"mz":"Mozambique",
	"na":"Namibia",
	"nc":"New Caledonia (France)",
	"ne":"Niger",
	"nf":"Norfolk Island",
	"ng":"Nigeria",
	"ni":"Nicaragua",
	"nl":"Netherlands",
	"no":"Norway",
	"np":"Nepal",
	"nr":"Nauru",
	"nu":"Niue",
	"nz":"New Zealand",
	"om":"Oman",
	"pa":"Panama",
	"pe":"Peru",
	"pf":"French Polynesia (France)",
	"pg":"Papua New Guinea",
	"ph":"Philippines",
	"pk":"Pakistan",
	"pl":"Poland",
	"pm":"Saint-Pierre and Miquelon (France)",
	"pn":"Pitcairn Islands (United Kingdom)",
	"pr":"Puerto Rico (United States)",
	"ps":"Palestine",
	"pt":"Portugal",
	"pw":"Palau",
	"py":"Paraguay",
	"qa":"Qatar",
	"re":"Réunion (France)",
	"ro":"Romania",
	"rs":"Serbia",
	"ru":"Russia",
	"rw":"Rwanda",
	"sa":"Saudi Arabia",
	"sb":"Solomon Islands",
	"sc":"Seychelles",
	"sd":"Sudan",
	"se":"Sweden",
	"sg":"Singapore",
	"sh":"Saint Helena, Ascension and Tristan da Cunha (United Kingdom)",
	"si":"Slovenia",
	"sk":"Slovakia",
	"sl":"Sierra Leone",
	"sm":"San Marino",
	"sn":"Senegal",
	"so":"Somalia",
	"sr":"Suriname",
	"ss":"South Sudan",
	"st":"São Tomé and Príncipe",
	"su":"Soviet Union",
	"sv":"El Salvador",
	"sx":"Sint Maarten (Kingdom of the Netherlands)",
	"sy":"Syria",
	"sz":"Eswatini",
	"tc":"Turks and Caicos Islands (United Kingdom)",
	"td":"Chad",
	"tf":"French Southern and Antarctic Lands",
	"tg":"Togo",
	"th":"Thailand",
	"tj":"Tajikistan",
	"tk":"Tokelau",
	"tl":"East Timor",
	"tm":"Turkmenistan",
	"tn":"Tunisia",
	"to":"Tonga",
	"tr":"Turkey",
	"tt":"Trinidad and Tobago",
	"tv":"Tuvalu",
	"tw":"Taiwan",
	"tz":"Tanzania",
	"ua":"Ukraine",
	"ug":"Uganda",
	"uk":"United Kingdom",
	"us":"United States of America",
	"uy":"Uruguay",
	"uz":"Uzbekistan",
	"va":"Vatican City",
	"vc":"Saint Vincent and the Grenadines",
	"ve":"Venezuela",
	"vg":"British Virgin Islands (United Kingdom)",
	"vi":"United States Virgin Islands (United States)",
	"vn":"Vietnam",
	"vu":"Vanuatu",
	"wf":"Wallis and Futuna",
	"ws":"Samoa",
	"ye":"Yemen",
	"yt":"Mayotte",
	"za":"South Africa",
	"zm":"Zambia",
	"zw":"Zimbabwe",
}

TLDs = {
  "com":"commercial",
  "co":"commercial", // Only used in UK? Won't mix up with Columbia, as uk would have been pop() already.
	"org":"organization",
	"net":"network",
	"int":"international",
	"edu":"education",
	"gov":"U.S. national and state government agencies",
	"mil":"U.S. military",
	"arpa":"Address and Routing Parameter Area",

  "academy":"Schools, military academies, online learning websites, PTAs and student portals, any site created to be educational on a particular topic",
	"accountant":"Certified Public Accountants, tax advisors, corporate accountants, personal and business accountants, professional CPA organizations",
	"accountants":"accountants and accounting firms",
	"active":"Reserved for Active Network",
	"actor":"Aspiring actors and their agents, theaters and movie studios, entertainment outlets, streaming video sites, movie review sites, celebrity gossip sites",
	"ads":"advertising",
	"adult":"adult entertainment (pornography)",
	"aero":"air-transport industry",
	"africa":"African and pan-African topics, African Union",
	"agency":"Marketing and advertising agencies, PR or communications agencies, design firms, talent agencies, travel agencies, other related agencies",
	"airforce":"Military recruiters, flight training schools, supply companies, military aircraft suppliers and repair companies, Air Force members and veterans",
	"amazon":"Reserved for Amazon",
	"analytics":"Reserved for SAS Institute",
	"apartments":"Property (apartment) managers, condominium/apartment developers, college websites/centers, city guides and community centers",
	"app":"Apps",
	"apple":"Apple",
	"archi":"architects and architect firms",
	"army":"Military recruiter, army supply stores, military training schools, army members and veterans",
	"art":"artists, museums, art galleries, dealers, service providers and contractors",
	"associates":"Accountants, law firms, consulting firms, real estate agencies, health & medical groups",
	"attorney":"Independent attorneys and law firms of any size, legal services entities, elected officials and judges, professional organizations, law students",
	"auction":"Auction houses & online auctions, car and truck auction, B2B commodity auctions, charity auctions for non-profits and schools, buyer and seller communities",
	"audible":"Reserved for Audible",
	"audio":"stereo/sound systems, music",
	"author":"Reserved for Amazon books",
	"auto":"vehicles",
	"autos":"vehicles",
	"aws":"Reserved for Amazon Web Services",
	"baby":"For selling baby products",
	"band":"Music venues, ticket sale/resale sites, music band & musician sites, school band sites, music review sites",
	"bank":"banks",
	"bar":"Bars and related industry",
	"barefoot":"Reserved for Gallo Vineyards Inc.",
	"bargains":"Online retailers, large and small, “sale” sections on retail websites, discount & overstock sites, bargain hunters, frugal-living bloggers",
	"baseball":"baseball",
	"basketball":"basketball",
	"beauty":"Reserved for L'Oréal",
	"beer":"breweries and beer aficionados",
	"best":"—",
	"bestbuy":"Reserved for Best Buy",
	"bet":"gambling",
	"bible":"Bible",
	"bid":"auctions",
	"bike":"Bicycle & motorcycle enthusiasts, bike retailers & gear shops, bike repair shops, biking event organizers, bike or motorcycle clubs",
	"bingo":"Bingo halls, casinos, online & casual gaming sites, travel agencies",
	"bio":"Organic agriculture",
	"biz":"business",
	"black":"those who like the color black",
	"blackfriday":"Black Friday, retail",
	"blockbuster":"Reserved for Blockbuster LLC",
	"blog":"Blogs",
	"blue":"those who like the color blue",
	"boo":"—",
	"book":"Reserved for Amazon books",
	"boots":"Reserved for Boots Company Ltd",
	"boston":"websites related to the city of Boston, Massachusetts USA",
	"bot":"Restricted to online `bots` using approved frameworks (Amazon Lex, Dialogflow, Gupshup, Microsoft Bot Framework, and Pandorabots) Amazon allows users to contact them if they have a bot outside of these frameworks.",
	"boutique":"Specialty online retailers, vintage shops, designers, artists and artisans, craftspeople",
	"box":"individuals and businesses, in order to promote personal cloud storage",
	"broadway":"Broadway theatre",
	"broker":"DOTBROKER REGISTRY LTD",
	"build":"construction industry",
	"builders":"Contractors, subcontractors, commercial/residential architects, interior designers",
	"business":"Creative businesses & agencies, freelancers & independent consultants, any other business looking to differentiate from the competition",
	"buy":"sales",
	"buzz":"marketing and social networking",
	"cab":"Airline & travel-related products or services, city guides & tourist attractions, transportation businesses, hotels, hostels, B&Bs, lodging, tourist attractions",
	"cafe":"Cafes, restaurants, delis, cafeterias, coffee shops & coffee stands, student lounges, mobile food/beverage vendors, cooking schools",
	"call":"Amazon Registry Services, Inc.",
	"cam":"entertainment",
	"camera":"Professional photographers, camera and equipment retailers, photo studios & photography schools, wedding and specialty photographers, anyone who wants to share photos online",
	"camp":"Camping/RV sites, travel writers & bloggers, outdoor adventure companies, summer camps for kids, hotels, hostels, lodges, bed & breakfast lodging",
	"cancerresearch":"Organizations, research institutes and individuals interested in ending cancer through research",
	"capital":"Mortgage companies, financial services professionals, investment services, venture capital investors",
	"car":"vehicles",
	"cards":"Occasion shoppers (holiday, birthday, bereavement), occasion-related websites, gift buyers, corporate HR departments",
	"care":"Surgeons, primary/secondary care physicians, insurance providers, hospitals & clinics, medical, dental, or vision specialists, service based products or services",
	"career":"jobs and job-searching",
	"careers":"Career services (coaching, resume writing), job sites & recruiters, business coaches, staffing firms, HR department of any business",
	"cars":"Automotive",
	"case":"Reserved for CNH Industrial",
	"cash":"Pawn shops and consignment shops, currency exchanges, other cash-based businesses, check cashing services",
	"casino":"Casino & online gaming sites, travel agencies, local tourist sites, hotel booking sites",
	"catering":"Caterers & personal chefs, specialty food vendors, wedding planners & event planners, event spaces, wholesale suppliers",
	"catholic":"Catholicism",
	"center":"Community centers, business centers, shopping centers, tourist sites/city centers, tutoring & learning centers",
	"cern":"CERN",
	"ceo":"CEOs",
	"cfd":"clothing fashion design; originally signified contracts for difference trading when applied for by IG Group Holdings plc",
	"channel":"Reserved for YouTube",
	"chat":"Online chat rooms, dating, political, religious, sports, human interest, & hobbyist forums, companies with live chat help desks, chatbot technology companies",
	"charity":"—",
	"cheap":"Online retailers, discount sites, overstock sites, businesses who sell bulk products at discounted prices, bargain hunters & frugal-living bloggers",
	"christmas":"Christmas",
	"church":"Churches, youth organizations, spiritual communities, religion-based organizations, anyone who publishes spiritual or religious content",
	"circle":"Reserved for Amazon",
	"city":"City resource sites for locals and travelers, travel writers & bloggers, local reviews websites, tourist attractions, transportation businesses",
	"claims":"Insurance adjusters & claims representatives, insurance claims departments (auto, medical, homeowners), customer service departments of insurance companies, law firms",
	"cleaning":"Contractors, commercial/home cleaning services, auto detailing/cleaning services",
	"click":"—",
	"clinic":"Healthcare clinics, medical or healthcare specialists, sports clinics, urgent care clinics",
	"clothing":"Online retailers, department stores, designers",
	"cloud":"Companies involved in cloud computing",
	"club":"groups, organizations, assemblies, communities, general",
	"coach":"Athletic organizations, personal trainers & coaches, business, life, & health coaches, school & community club coaches or tutors, affordable travel, airline, train, car, or other transportation companies",
	"codes":"Software and web developers, IT companies, technology R&D companies, coding enthusiasts, coding classes & camps",
	"coffee":"Coffee shops, roasters, wholesalers & suppliers, machine & equipment suppliers and stands",
	"college":"Educational",
	"community":"City guides & community centers, online communities, neighborhood associations, churches, mosques, temples, and other spiritual communities, local writers & bloggers",
	"company":"Small, medium, or large businesses, business that want to demonstrate authority in their field, makers, artisans, anyone who sells a niche product",
	"compare":"Reserved for iSelect Ltd",
	"computer":"Computer manufacturers, computer repair services, computer resellers, computer training & education programs, tech companies",
	"condos":"Real estate brokers/agents, property (condominium) managers, mortgage companies, condominium/apartment developers, condominium associations",
	"construction":"Contractors, commercial/residential architects, wholesale and retail construction suppliers",
	"consulting":"Consulting firms, independent consultants, specialty services, businesses that offer expert training",
	"contact":"Top Level Spectrum, Inc.",
	"contractors":"Construction-related businesses, contractors, subcontractors, independent contractors with unique skills and expertise, unions or other organizations promoting their people and skills",
	"cooking":"sharing recipes",
	"cool":"Fashion magazines & blogs, meme aggregators, trend tracking sites, online merchants, fun publications & sites",
	"coop":"cooperatives",
	"country":"general",
	"coupon":"discounts and rebates",
	"coupons":"Coupon pages, coupon sites, discount sites, coupon-themed blogs, bargain hunters",
	"courses":"education",
	"cpa":"accountants and accounting firms",
	"credit":"Credit card companies, lenders, credit unions, collection agencies, credit counselors & financial planners",
	"creditcard":"Credit card companies, store/retailer credit card sites, credit counselors & financial planners, credit card processing services",
	"cruise":"Cruise lines, cruise-related products or services, travel agencies & vacation services, private charter boats",
	"cricket":"cricket",
	"cruises":"cruise businesses and travel",
	"cyou":"For any individual or business that shares the ethical values of diversity, inclusivity, and independence",
	"dad":"families",
	"dance":"Dance studios & instructors, nightclubs & music venues, dance teams & troupes, dance shoe, clothing & equipment manufacturers, fans of dance & live performances",
	"data":"Dish DBS Corporation",
	"date":"online dating",
	"dating":"Dating & matchmaker sites, travel sites & city guides, singles meetup groups, traditional “classified” sites, event businesses",
	"day":"general",
	"deal":"sales",
	"deals":"Discount sites, bargain hunters, coupon sites, coupon pages. coupon-themed guides, directories and blogs",
	"degree":"Brick-and-mortar schools & universities, online universities, other learning courses, other educational resources",
	"delivery":"Consumer delivery services, commercial shipping services, transportation services, messenger services, any business that ships their products",
	"democrat":"Political candidates, lobbyists, political parties, fundraising organizations",
	"dental":"Dentists, endodontists, orthodontists, retailers selling oral health supplies, wholesale suppliers for dental care",
	"dentist":"Dentists, endodontists, orthodontists, retailers selling oral health supplies, wholesale suppliers for dental care",
	"design":"graphic art and fashion",
	"dev":"software development",
	"diamonds":"Jewelers, diamond wholesalers and retailers, jewelry appraisers and buyers, pawn shops",
	"diet":"dieting and dietary",
	"digital":"Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), online event, meetup & gaming sites, technology companies, e-commerce sites",
	"direct":"Direct-to-consumer stores, bargain hunters, transportation services, messenger services, delivery & shipping services",
	"directory":"Listings organizations, name, phone & address directories, online business directories, clubs, groups, & other organizations directories",
	"discount":"Discount sites, bargain hunters, coupon sites, coupon pages, coupon-themed blogs",
	"diy":"do-it-yourself",
	"docs":"Medical doctors",
	"doctor":"Doctors, any business with “doctor” in the name, other health care providers, PhD experts in any field",
	"dog":"Dog breeders, dog walking, grooming & sitting businesses, veterinarians, animal shelters & adoption centers, pet stores & suppliers",
	"domains":"Any web-based service, network consultants, domain brokers, resellers and registrars, home-related products and services",
	"dot":"Dish DBS Corporation",
	"download":"technology",
	"drive":"Reserved for Google Drive",
	"duck":"Reserved for Duck®",
	"earth":"Individuals or businesses with a worldwide focus",
	"eat":"restaurants and foodies",
	"eco":"Sustainability minded companies, non-profits and professionals.",
	"education":"Colleges & universities, public schools, PTAs & other school groups, education research organizations, any organization focused on educating its audience",
	"email":"Advertising/Marketing/PR/Design agencies, email marketing experts, CRM and marketing technology specialists, anyone who wants a memorable email address",
	"energy":"Electrical, mechanical, chemical, nuclear & thermal energy producers, solar, wind, hydro, bio & other sustainable alternative energy producers, battery manufacturers & oil industry R&D, energy conservation organizations, energy food & drink manufacturers",
	"engineer":"Computer and software engineering companies, civil, electrical, mechanical, and architectural engineering companies, environmental, chemical, geotechnical, and bio engineering companies, engineer training or educational institutions, railroad engineers",
	"engineering":"Computer and software engineering companies, civil, electrical, mechanical, and architectural engineering companies, environmental, chemical, geotechnical, and bio engineering companies, engineer training or educational institutions, railroad engineers",
	"edeka":"edeka firms",
	"entertainment":"Ticket outlets, travel sites & local tourist sites, performance halls, theaters, & music venues, anyone in the entertainment industry, celebrity news sites",
	"enterprises":"Entrepreneurs, startups, parent & holding companies, enterprise SaaS solutions & tech services",
	"equipment":"Home improvement stores, construction equipment rentals, construction equipment sales, sporting goods stores",
	"esq":"lawyers, law firms, legal professionals",
	"estate":"Estate sale management & appraisal services, estate planners & lawyers, real estate agents & brokers",
	"events":"Event planners, sports & gaming agencies/sites, ticket sale/resale sites, city guides & community centers, performance halls, music clubs/bars",
	"exchange":"Foreign currency exchanges, stock brokers, investment fund traders, ETF distributors, brokers, & dealers",
	"expert":"Home services providers, online review sites, skilled worker databases, freelanceers, consultants, & subject matter experts",
	"exposed":"Tabloid sites, celebrity romance blog, TV spoiler sites, sites that host leaked documents, investigative journalism sites",
	"express":"Transportation services, messenger services, delivery & shipping services, direct-to-consumer stores",
	"fail":"Online meme aggregators, humor websites, video sites",
	"faith":"religion and churches",
	"family":"Family-focused travel sites, blogs about family-friendly activities & games, family history sites, photo sites, obstetricians & family practice doctors",
	"fan":"Fan sites, current events & gossip sites, sport blogs and forums, personal & business sites about niche topics",
	"fans":"general",
	"farm":"Real estate brokers/agents, farming services & equipment dealers, farmers & ranchers, property managers, health food distributors, cryptocurrency farmers",
	"fashion":"clothing industry",
	"fast":"Reserved for Amazon",
	"feedback":"feedback and reviews",
	"fiat":"Only FIAT S.P.A. and its Affiliates (and qualifying Trademark Licensees as defined in, and in accordance with Specification 13 of the Registry Agreement (“Specification 13”) where applicable) are eligible to register a Domain Name under the .FIAT TLD.",
	"film":"films",
	"final":"final versions of anything",
	"finance":"Investment services, banks & financial institutes, credit counselors & financial planners, accounting firms, lenders",
	"financial":"Investment services, banks & financial institutions, credit counselors & financial planners, accounting firms, lenders",
	"fire":"Reserved for Amazon (promotion of Fire devices)",
	"fish":"Seafood markets, restaurants & suppliers, sport fishing & fly fishing enthusiasts, fishing gear, tackle, & product manufacturers, travel outfitters & fishing guide companies, aquariums, pet & fish supply stores, marine biology programs & conservation organizations",
	"fishing":"fishing businesses, sports, and interests",
	"fit":"Fitness and exercise",
	"fitness":"Gyms, athletic clubs & family health organizations, personal trainers, weight loss, health & wellness clinics, health & exercise blogs, fitness competition & events companies",
	"flights":"Airline-related products or services, helicopter rides, skydiving, & hang gliding, travel agencies & travel services, private pilots, airport transportation",
	"florist":"Florists, flower delivery services, floral designers, flower seed suppliers",
	"flowers":"florists and gardens",
	"fly":"travel",
	"foo":"web development",
	"food":"Lifestyle Domain Holdings, Inc.",
	"foodnetwork":"Reserved for Food Network",
	"football":"Professional & amateur football & soccer teams, football clothing, gear & fan merchandise, football equipment manufacturers, football coaches & players",
	"forsale":"Individual real estate brokers and brokerages, wholesalers and retailers across many product categories, discount, flash sale and deal websites, auction sites and individuals selling items they no longer need",
	"forum":"forums",
	"foundation":"Charitable organizations, public school foundations, other philanthropic organizations & foundations",
	"free":"sales",
	"frontdoor":"Reserved for HGTV",
	"fun":"—",
	"fund":"Investment services, banks & financial institutions, credit counselors & financial planners, lenders",
	"furniture":"Home décor and furnishing stores, department stores, home designers, vintage stores, antique dealers",
	"fyi":"for your information",
	"gallery":"Galleries, professional photographers, camera and equipment retailers, photo studios & photography schools, wedding and specialty photographers, anyone who wants to share photos online",
	"game":"gaming",
	"games":"Gaming sites, forums & reviews, online or brick & mortar game stores/clubs, sports events, clubs—professional & recreational, casinos",
	"garden":"gardening",
	"gay":"gay individuals or supportive organisations",
	"gdn":"general",
	"gift":"gift-giving",
	"gifts":"Gift buyers, discount sites, corporate HR departments, bargain hunters",
	"gives":"Philanthropic organizations and foundations, charities, nonprofits, corporate giving initiatives, volunteer organizations",
	"glass":"Glass & glass repair shops, glass departments within home supply stores, contractors, windshield repair & auto glass businesses, DIYers/artists",
	"gle":"Google abbreviations",
	"global":"general, companies or individuals with a global focus or presence",
	"gold":"Jewelers, gold traders and dealers, coin sellers and traders, trophy and awards shops",
	"golf":"Professional & amateur golf organizations, golf courses, equipment suppliers & manufacturers, golf travel & event companies, golf players, enthusiasts & spectators, sports networks",
	"google":"Google",
	"gop":"Republican Party politics",
	"graphics":"Web design firms, freelance designers, graphic artists",
	"green":"the environmentally-focused",
	"gripe":"Online complaint sites, online forums, customer service providers, feedback sites, blogs about scams",
	"grocery":"Reserved for Walmart",
	"group":"Groups based on hobbies or interests (running, crafts, gaming), group-based businesses (medical practices, law firms, financial advisors), professional associations, support groups",
	"guide":"City resource sites for locals and travelers, travel writers & bloggers, local reviews websites, tourist attractions & guides, outdoor adventure companies",
	"guitars":"Guitars",
	"guru":"Mindfulness & yoga practices, spiritual leadership sites, any training program, work-for-hire sites, freelancers, consultants, & subject matter experts",
	"hair":"haircare products and services",
	"hangout":"Reserved for Google Hangouts",
	"health":"health and related topics",
	"healthcare":"Primary/secondary care physicians, hospitals & clinics, healthcare insurance providers & brokers, company HR/benefits departments",
	"help":"help sites",
	"here":"generic geographic",
	"hiphop":"Hip hop culture",
	"hiv":"AIDS and HIV awareness",
	"hockey":"Sports media, sporting goods stores & hockey equipment suppliers, professional, minor league & amateur hockey teams, hockey fans, fantasy leagues, sponsors, coaches & referees",
	"holdings":"Holding companies, private equity firms, real estate developers",
	"holiday":"Airline-related products or services, travel agencies, resources & services, travel writers & bloggers, city guides & resource sites, hotels, hostels, B&Bs, lodging",
	"homegoods":"Reserved for HomeGoods",
	"homes":"real estate professionals",
	"homesense":"Reserved for HomeSense",
	"horse":"horse-related businesses and interest",
	"hospital":"Hospitals & clinics, healthcare providers, medical, dental, or vision specialists, insurance providers",
	"host":"network companies",
	"hosting":"—",
	"hot":"Amazon Registry Services, Inc.",
	"hotels":"Reserved for Booking.com",
	"house":"Real estate brokers/agents, mortgage companies, home builders, construction/home improvement suppliers, home improvement sites & blogs",
	"how":"how-to guides",
	"ice":"Reserved for Intercontinental Exchange",
	"icu":"entrepreneurs and business owners",
	"inc":"Corporations",
	"industries":"Machine or equipment manufacturers, manufacturers, tech or biotech companies, professional associations, businesses with “industries” in their names",
	"info":"information",
	"ing":"Verbal suffix: e.g., `jump.ing`.",
	"ink":"creative printing or tattooing",
	"institute":"Educational institutions, training programs, foundations, research organizations, military schools",
	"insurance":"insurance companies",
	"insure":"Insurance companies (life, auto, homeowners, renters), insurance divisions of larger companies (car rentals, warranties), insurance brokers & advisors",
	"international":"Any organization with an international presence, international consultants, import/export businesses, international travel organizations",
	"investments":"Investment services (institutional, private), wealth management services, financial planners, brokerage firms",
	"irish":"Airline-related products or services, domestic/International travel agencies, resources & services, travel writers & bloggers, Ireland travel guides & resource sites, seasonal opportunities (St. Patrick's Day)",
	"jewelry":"Jewelers, jewelry buyers, online retailers, department stores",
	"jobs":"Employment",
	"joy":"Reserved for Amazon",
	"kim":"Kim (Korean surname)",
	"kitchen":"Restaurants, cafes, & delis, food stands & mobile vendors, meal services & personal chefs, kitchen supply stores, food blogs & recipe sites",
	"kosher":"Kosher food certification and regulations",
	"land":"Real estate brokers and agents, residential/commercial land developers, home builders, mortgage companies, traditional “classified” sites",
	"lat":"Latin American communities and users",
	"law":"practitioners and educators in law",
	"lawyer":"Independent attorneys and law firms of any size, legal services entities, elected officials and judges, professional organizations, law students",
	"lease":"Real estate brokers/agents, property managers, condo/apartment developers, real estate law firms",
	"leclerc":"Reserved for E.Leclerc",
	"legal":"Attorneys, lawyers & law firms, corporate legal teams, paralegals, legal advocates, committees, associations and interest groups associated with the law",
	"lgbt":"the lesbian, gay, bisexual and transgender community",
	"life":"Wellness and health experts, charities, coaches & personal development enthusiasts, lifestyle bloggers, anyone who wants to share personal stories",
	"lifeinsurance":"life insurance",
	"lighting":"Lighting & lighting repair shops, lighting departments within home supply stores, contractors, commercial/residential architects, DIYers",
	"like":"Amazon Registry Services, Inc.",
	"limited":"Private companies, limited by shares, limited companies, businesses with “limited” or “LTD” in their names, specialty products and services, businesses that sell limited-quantity products",
	"limo":"Airline & travel-related products or services, city guides & tourist attractions, transportation businesses, hotels, lodging, weddings, party and occasion-related services",
	"link":"connecting to information",
	"live":"Live streaming sites, entertainment/music venues, news sites/blogs, ticket sale/resale sites, video production companies",
	"living":"Lifestyle Domain Holdings, Inc.",
	"loan":"banks and lenders",
	"loans":"Mortgage companies, personal loan agencies, auto loan agencies & car dealerships, credit consolidation services",
	"locker":"Reserved for DISH DBS Corporation",
	"lol":"LOL: laughing out loud (humorous or comedic content)",
	"lotto":"lottery",
	"love":"dating sites",
	"ltd":"Private companies, limited by shares, limited companies, businesses with “limited” or “LTD” in their names, specialty products and services, businesses that sell limited-quantity products",
	"luxury":"businesses catering to the wealthy",
	"makeup":"Reserved for L'Oréal",
	"management":"Property managers, wealth management firms, money management, systems & network managers, leadership teams",
	"map":"maps and navigation",
	"market":"Online retailers, independent or chain grocery stores, buyer and seller communities, discount sites & coupon sites",
	"marketing":"Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), staffing agencies, marketing consultants",
	"markets":"Reserved for IG Group",
	"mba":"Colleges, universities, & graduate programs, online educational sites, job search sites, MBA candidates",
	"med":"medicine and related topics",
	"media":"Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), news outlets, media bloggers, celebrity publications, digital publishers & graphic designers",
	"meet":"social gatherings, meeting new people",
	"meme":"Internet memes",
	"memorial":"News site obituaries, personal tribute sites, floral & funeral arrangement companies",
	"men":"men",
	"menu":"restaurants",
	"mint":"Reserved for Intuit Mint",
	"mobi":"mobile devices",
	"mobile":"Dish DBS Corporation",
	"mobily":"Reserved for Mobily",
	"moe":"Japanese otaku culture; see moe (slang)",
	"mom":"mothers",
	"money":"Lenders, financial services businesses, money blogs & news sites, investment bankers & brokers, financial planners & experts",
	"monster":"Reserved for Monster.com",
	"mortgage":"Mortgage brokers, real estate brokers/agents, home buyers, traditional “classified” sites",
	"motorcycles":"motorcycles",
	"mov":"digital video",
	"movie":"Streaming movie services, movie studios & distributors, movie theaters & entertainment outlets, ticket sale/resale sites, movie review sites",
	"museum":"museums",
	"music":"Music dissemination and appreciation",
	"name":"individuals, by name",
	"navy":"Naval training schools, navy supply stores, military recruiters, credit unions, navy members and veterans",
	"network":"IT professionals, tech consultants, career sites, industry-specific professional groups, social networks",
	"new":"Websites where people can create something",
	"news":"News organizations, educational publications, trade publications, neighborhood news blogs",
	"ngo":"Non-governmental organizations.",
	"ninja":"Sites promoting specialized skills, repair services (auto, appliance, etc.), gaming sites, martial arts organizations",
	"now":"Amazon Registry Services, Inc.",
	"ntt":"Restricted to use by NTT Japan. Refer to the .ntt Registration Policies page for more information.",
	"observer":"Reserved for The Observer",
	"off":"Reserved for Off!",
	"org":"general",
	"one":"general",
	"ong":"Non-governmental organizations.",
	"onl":"generic",
	"online":"generic",
	"ooo":"general",
	"open":"private to the `Registry Operator and its qualified Affiliates and Trademark Licensees`",
	"organic":"organic gardeners, farmers, foods, etc.",
	"origins":"Reserved for Origins",
	"page":"Reserved for Google and related content",
	"partners":"Law firms, real estate agencies, investment firms, accounting firms, nonprofit organizations",
	"parts":"Appliance wholesalers & service, tool rentals & service businesses, auto/boat/heavy equipment businesses",
	"party":"nightclubs and social gatherings",
	"pay":"electronic payments",
	"pet":"animals and pets",
	"pharmacy":"pharmacies",
	"phone":"telephone-related businesses",
	"photo":"photography and photo-sharing",
	"photography":"Professional photographers, camera and equipment retailers, photo studios & photography schools, wedding and specialty photographers, anyone who wants to share photos online",
	"photos":"Professional photographers, camera and equipment retailers, photo studios & photography schools, wedding and specialty photographers, anyone who wants to share photos online",
	"physio":"physical therapists",
	"pics":"photography and photo-sharing",
	"pictures":"Professional photographers, camera and equipment retailers, photo studios & photography schools, wedding and specialty photographers, anyone who wants to share photos online",
	"pid":"personal identification",
	"pin":"Reserved for Amazon",
	"pink":"those who like the color pink",
	"pizza":"Pizzerias, take & bake pizza shops, Italian or Greek restaurants, pizza brands found in grocery stores",
	"place":"Airline-related products or services, travel agencies, resources & services, travel writers & bloggers, tourist attractions, hotels, hostels, B&Bs, lodging",
	"plumbing":"Plumbers & plumbing repair businesses, plumbing departments within home supply stores, contractors/subcontractors, DIYers",
	"plus":"Consumer commodity stores & sites, clothing (plus, big & tall), service-based businesses, any entity wanting to show their competitive advantage",
	"poker":"Poker players and sites",
	"porn":"adult entertainment (pornography)",
	"post":"postal services",
	"press":"publishing and journalism",
	"prime":"Reserved for Amazon Prime",
	"pro":"professions/professionals",
	"productions":"Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), video production services, anyone in the film industry",
	"prof":"Professors, teachers and learning",
	"promo":"advertising",
	"properties":"Real estate brokers/agents, residential/Commercial land developers, property (condo/apartment) managers, home builders, mortgage companies",
	"property":"real estate",
	"protection":"security",
	"pub":"Pubs, bars & nightclubs, burger joints, breweries & taphouses, beer distributors, restaurant & bar suppliers publications",
	"qpon":"coupons",
	"quebec":"—",
	"racing":"racing",
	"radio":"radio stations",
	"read":"Reserved for Amazon books",
	"realestate":"real estate",
	"realtor":"realtors",
	"realty":"realty and housing",
	"recipes":"Recipe sites, food & beverage grocery brands, health & fitness organizations, cooking enthusiasts, personal/professional chefs",
	"red":"those who like the color red",
	"rehab":"Physical and occupational therapists and professionals, drug, alcohol and gambling addiction counselors, rehabilitation facilities and recovery centers, online health directories, physical or emotional health associations",
	"reit":"real estate investment trusts",
	"rent":"Real estate professionals and small businesses",
	"rentals":"Real estate brokers/agents, city guides, college housing centers, & community centers, vehicle, equipment, or entertainment/event rentals, property managers, condo/apartment developers",
	"repair":"General or specialty repair shops, construction contractors/subcontractors, DIYers, appliance wholesalers & service, auto/boat businesses",
	"report":"News and current events sites, financial reporting sites, financial or business analysts, consumer product reviews, police, school, or other community report listings",
	"republican":"Political candidates, lobbyists, political parties, fundraising organizations",
	"rest":"Restaurants and related industry",
	"restaurant":"Casual eateries, gourmet restaurants, suppliers, chains, review sites, reservation sites & services",
	"review":"public reviews",
	"reviews":"News media, food publications, travel publications, literary publications, any product & service with online reviews",
	"rich":"businesses catering to the wealthy",
	"rip":"Loved ones seeking to memorialize the deceased, funeral homes and cemeteries, businesses that support the funeral industry, obituary websites",
	"rocks":"Pop culture sites, niche and fan sites, musicians, gemstone & jewelry companies",
	"rodeo":"Rodeo interest",
	"room":"lodging or room design",
	"rugby":"rugby",
	"run":"Runners, running shoe retailers, specialty running gear shops, running event organizers",
	"safe":"security and safety",
	"sale":"Online and brick-and-mortar retailers and wholesalers, automotive and motorcycle dealers, discount, flash sale, and deal websites, auction sites and individuals selling items they no longer need",
	"salon":"Hair salons, nail salons, beauty product companies, beauty schools",
	"save":"Amazon Registry Services, Inc.",
	"sbi":"State Bank of India",
	"scholarships":"scholarship related",
	"school":"Public schools, private & charter schools, specialty and trade schools, online learning sites, resource sites for teachers",
	"science":"science-related sites",
	"search":"search engines",
	"secure":"security",
	"security":"XYZ.COM LLC",
	"select":"iSelect Ltd",
	"services":"Service division of any company, home services (cleaning, landscaping, plumbing, pet care), business services (tech support, interior design, translation services), community service organizations",
	"sex":"adult entertainment (pornography)",
	"sexy":"adult entertainment",
	"shoes":"Shoe stores, department stores, online retailers, athletic shoe retailers, discount shoe stores",
	"shop":"GMO Registry, Inc.",
	"shopping":"Online retailers, shopping centers, personal shoppers, discount sites & coupon sites, shopping blogs & product reviews",
	"show":"Ticket sale/resale sites, performance halls, music clubs/bars, streaming video services, movie review sites, travel sites & city guides",
	"showtime":"Reserved for Showtime",
	"silk":"Reserved for Amazon Silk",
	"singles":"(Tickets) Ticket sale/resale sites, gaming agencies, movie review sites, city guides, sports sites\n(Dating) Dating & matchmaker sites, singles meetup groups, traditional “classified” sites, travel sites & city guides",
	"site":"general",
	"ski":"skiing",
	"skin":"Reserved for L'Oréal",
	"sky":"Sky International AG",
	"sling":"Reserved for Sling Media",
	"smile":"Reserved for Amazon",
	"sncf":"Reserved to the SNCF company.",
	"soccer":"Professional & amateur soccer clubs, soccer equipment suppliers & manufacturers, soccer & sports media networks, soccer players, enthusiasts, & spectators, soccer camps, coaches, & training organizations",
	"social":"Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), blogs & forums, event & meetup groups, any person or organization driving awareness of their social presence",
	"software":"Software testing, support, & consulting companies, software product developers & manufacturers, software training & educational institutions, software resellers",
	"solar":"Renewable & sustainable energy producers, solar panel, roof tile, & storage producers, solar cell battery, chargers, lights, speakers, & generator manufacturers, sunglass, shades, UV clothing, sunblock & other solar protection products",
	"solutions":"SaaS providers, people who offer do-it-yourself tips and tutorials, consultants, any business focused on providing the right solutions to their customers’ problems.",
	"song":"Reserved for Amazon Music",
	"spa":"Spas",
	"space":"as a creative space",
	"spreadbetting":"Spread betting",
	"spot":"Amazon Registry Services, Inc.",
	"sport":"sport institutions",
	"srl":"Spanish/Italian/Romanian/French limited liability companies",
	"stockholm":"Stockholm municipality in Sweden",
	"storage":"Self storage",
	"store":"stores",
	"stream":"streaming media",
	"studio":"Advertising/Marketing/PR/Design agencies, creative freelancers, other creative agencies (i.e., animation, production), dance, yoga, or fitness studios",
	"study":"education",
	"style":"Fashion bloggers, department stores, designers, online retailers",
	"sucks":"gripe sites",
	"supplies":"Contractors, distribution companies, appliance wholesalers & service, auto/boat/heavy equipment businesses, home services retailers",
	"supply":"Contractors, distribution companies, appliance wholesalers & service, auto/boat/heavy equipment businesses",
	"support":"IT/Tech support services, social services, customer service & support departments, independent consultants & consulting firms, staffing services",
	"surf":"surfing",
	"surgery":"Surgeons, primary/secondary care physicians, hospitals & clinics, healthcare providers, insurance providers",
	"systems":"IT businesses, other tech-focused businesses, businesses that sell electronics or home security systems, organizational consultants",
	"talk":"Amazon Registry Services, Inc.",
	"tattoo":"tattoo aficionados",
	"tax":"Accounting & bookkeeping firms, tax advisors, auditors, financial experts & advisors",
	"taxi":"Airline & travel-related products or services, city guides & tourist attractions, transportation businesses, hotels, hostels, B&Bs, lodging, tourist attractions",
	"team":"Professional & amateur sports teams, sports equipment suppliers & manufacturers, sports media, athletes & fans, clubs, online communities & business organizations",
	"tech":"technology",
	"technology":"Tech-focused businesses & tech startups, businesses that sell to tech companies, developers, coders, programmers, computer retailers, technology blogs, news sites, & review sites, hardware & software companies, R&D companies, tech product manufacturers",
	"tel":"internet communication services",
	"tennis":"Tennis courts, clubs & other venues, tennis equipment suppliers and retailers, professional & amateur tennis players, sports media",
	"theater":"Entertainment & movie theater outlets, live performance theaters, professional performer associations, movie review sites, travel sites & city guides",
	"theatre":"theatre",
	"tickets":"ticket resale",
	"tips":"Travel, hotel & hospitality companies, cooking & recipe publications, parenting & and relationship publications, manufacturers of any product with assembly instructions, publications that provide advice on gratuity practices around the world",
	"tires":"Tire wholesalers, tire retailers, auto repair shops",
	"today":"News & current event sites, websites that publish daily content, daily inspiration sites, sites with daily rotating deals or offers, anyone who wants to spur immediate action",
	"tools":"Tool shops, tool departments within home supply stores, contractors, subcontractors, construction-related businesses",
	"top":"general",
	"tours":"Airline-related products or services, travel agencies, resources & services, tourist attractions, outdoor adventure companies, private plane/helicopter tours & services",
	"town":"Travel agencies, resources & services, local business associations, city guides & resource sites, transportation businesses, hotels, hostels, B&Bs, lodging",
	"toys":"Toy stores, online retailers, department stores, game companies, sporting goods companies",
	"trade":"businesses",
	"trading":"DOTTRADING REGISTRY LTD",
	"training":"Personal trainers & nutrition coaches, gyms and fitness centers, sports medicine practitioners, business that sell sports gear or apparel, or fan merchandise, animal trainers, career or vocational training centers",
	"travel":"Airline-related products or services, travel agencies, resources, bloggers & services, city guides & tourist attractions, transportation businesses, destination resorts, hotels, hostels, B&Bs, lodging, any other travel or transportation business",
	"travelersinsurance":"Reserved for Travelers Insurance",
	"trust":"Artemis Internet Inc",
	"tube":"Latin American Telecom LLC",
	"tunes":"Reserved for Amazon Music",
	"uconnect":"Not assigned",
	"university":"Online universities, brick-and-mortar universities, university-related clubs & organizations",
	"uno":"general, Spanish and Italian speakers, Uno (card game)",
	"vacations":"Airline-related products or services, travel agencies, resources, bloggers & services, city guides & tourist attractions, transportation businesses, destination resorts, hotels, hostels, B&Bs, lodging",
	"ventures":"Venture capital investment firms, business financial services, business consultants, programs & services for entrepreneurs",
	"vet":"Veterinarians, veterinary clinics and hospitals, wholesale suppliers for veterinary supplies",
	"video":"Video production & media companies, videographers, video editors, script writers, & producers, streaming video sites services, creative agencies",
	"villas":"International real estate brokers/agents, international travel agencies, resources & services, travel writers & bloggers, traditional “classified” sites",
	"vin":"Wineries, wine shops & wine bars, wine distributors, wine clubs & online retailers, wine review sites and apps",
	"vip":"Very important persons",
	"vision":"Opticians & optometry clinics, healthcare providers, insurance provider, glasses retailers, online and brick & mortar",
	"vodka":"vodka-related businesses and interest",
	"volvo":"Only Volvo Holding Sverige Aktiebolag and its Affiliates are eligible to register a Domain Name under the .volvo Domain [73]",
	"vote":"democratic elections and campaign websites",
	"voting":"polling sites",
	"voyage":"Airline-related products or services, travel agencies, resources, bloggers & services, city guides & tourist attractions, transportation businesses, hotels, hostels, B&Bs, lodging",
	"wang":"general",
	"watch":"Watchmakers, jewelry stores, watch repair shops, neighborhood watch groups",
	"watches":"watches",
	"weather":"Reserved for The Weather Channel",
	"webcam":"web cam shows and video sharing",
	"website":"general",
	"wed":"engaged couples and wedding-oriented businesses",
	"wedding":"wedding-oriented businesses",
	"whoswho":"Who's Who (general)",
	"wiki":"wikis",
	"win":"games, Microsoft Windows",
	"wine":"Wineries, wine bars, wine shops, wine distributors, wine clubs & online retailers, wine review sites",
	"winners":"Reserved for TJX Companies",
	"work":"general",
	"works":"Contractors, distribution companies, appliance wholesalers & service, auto/boat/heavy equipment businesses, companies with solution based products or services",
	"world":"Brands with an international presence, nonprofits and charities, travel agencies & adventure companies, world travelers & global communities, any business with “world” in its name",
	"wow":"Amazon Registry Services, Inc.",
	"wtf":"Bargain websites, photo & video aggregators, meme sites, news of the weird",
	"xxx":"adult entertainment (pornography)",
	"xyz":"general",
	"yachts":"yachts",
	"yoga":"yoga",
	"you":"Amazon Registry Services, Inc.",
	"youtube":"Reserved for YouTube",
	"zero":"Amazon Registry Services, Inc.",
	"zip":"digital storage information, providers, and related entities",
	"zone":"Sports fans, technology groups & followers, entertainment, fairs, destinations with a “zone”, city planners & zoning regulators, any topic with a following",
}

function parse_protocol(protocol) {
  return typeof protocol=="string" ? protocol.toLowerCase() : null;
}

function parse_domain(domain) {
  // Parse domain into components.
  // Recognises typical country specific TLDs like .us/.uk/.cn etc.
  // If a standard TLD is found like .com/.commercial/.academy etc, it will be put in .tld.
  // For the rest of the domain levels, the lowest level will be considered .sld.
  // Any remaining domain levels will be split and stored as .subdomains.
  // 
  // For example:
  // _domain = "translate.google.com.hk";
  // _parsed={
  //   "full":"translate.google.com.hk",
  //   "list":[
  //     "translate",
  //     "google",
  //     "com",
  //     "hk"
  //   ],
  //   "country_tld":"hk",
  //   "country_name":"Hong Kong",
  //   "tld":"com",
  //   "tld_type":"commercial",
  //   "sld":"google",
  //   "subdomains":[
  //     "translate"
  //   ],
  //   "short":"google.com.hk"
  // }

  domain_levels = domain.split(".");

  domain_dict = {
    "full":domain,
    "list":[...domain_levels],
    "country_tld":null,
    "country_name":null,
    "tld":null,
    "tld_type":null,
    "sld":null,
    "subdomains":[],
    "short":null,
  }

  // Get the last domain level
  domain_level =  domain_levels.pop();
  
  // Check for ccTLDs
  if (Object.keys(ccTLDs).indexOf(domain_level.toLowerCase()) > -1){
    domain_dict.country_tld = domain_level;
    domain_dict.country_name = ccTLDs[domain_dict.country_tld.toLowerCase()];
    domain_level = domain_levels.pop();
  }

  // Check for TLDs
  if (Object.keys(TLDs).indexOf(domain_level.toLowerCase()) > -1){
    domain_dict.tld = domain_level;
    domain_dict.tld_type = TLDs[domain_dict.tld.toLowerCase()];
    domain_level = domain_levels.pop();
  } else if (domain_dict.country_tld) {
    // we have no TLD but we have ccTLD; then the ccTLD is considered the TLD
    domain_dict.tld = domain_dict.country_tld;
    domain_dict.country_tld = null;
  }

  // This must be SLD
  domain_dict.sld = domain_level;

  // The rest are subdomains
  domain_dict.subdomains = domain_levels;

  // Put together the company domain
  short_domain_parts = [domain_dict.sld];
  if (domain_dict.tld) { short_domain_parts.push( domain_dict.tld ) }
  if (domain_dict.country_tld) { short_domain_parts.push( domain_dict.country_tld ) }
  domain_dict.short = short_domain_parts.join(".");

  return domain_dict
}

function parse_paths(paths) {
  // Parse paths into its components.
  // A simple split using "/";
  // empty Array if not present.
  return paths ? paths.split("/") : [];
}

function parse_args(args) {
  // Parse args into a diciontary of lists.
  // For example:
  // _args = "?sl=en&tl=zh-TW&text=Testing%20Google%20Translate&op=translate"
  // _parsed = {
  //   "sl":[
  //     "en"
  //   ],
  //   "tl":[
  //     "zh-TW"
  //   ],
  //   "text":[
  //     "Testing%20Google%20Translate"
  //   ],
  //   "op":[
  //     "translate"
  //   ]
  // }
  // Note that urls allow for args to repeat, i.e. ?arg1=1&arg1=2&arg1=3,
  // hence all args will be returned as lists, { "arg1":[1,2,3] } in this case.
  args_dict = {}

  if (args) {
    args = args.split("&");
    
    for (id in args){
      arg = args[id].split("=");

      arg_key = arg[0].trim();
      arg_value = (arg.length>=2) ? arg.slice(1).join("=") : true;

      if (!args_dict[arg_key]) {
        args_dict[arg_key] = [];
      }
      args_dict[arg_key].push(arg_value);
    }
  }
  
  return args_dict;
}

function parse_url(url) {
  // Parse a URL into its components, and return a JSON object containing all the parts.
  // An example is:
  // 
  // _url = "https://translate.google.com.hk/?sl=en&tl=zh-TW&text=Testing%20Google%20Translate&op=translate"
  // _parsed = {
  //   "protocol":"https",
  //   "domain":{
  //     "full":"translate.google.com.hk",
  //     "list":[
  //       "translate",
  //       "google",
  //       "com",
  //       "hk"
  //     ],
  //     "country_tld":"hk",
  //     "country_name":"Hong Kong",
  //     "tld":"com",
  //     "tld_type":"commercial",
  //     "sld":"google",
  //     "subdomains":[
  //       "translate"
  //     ],
  //     "short":"google.com.hk"
  //   },
  //   "path":[],
  //   "args":{
  //     "sl":[
  //       "en"
  //     ],
  //     "tl":[
  //       "zh-TW"
  //     ],
  //     "text":[
  //       "Testing%20Google%20Translate"
  //     ],
  //     "op":[
  //       "translate"
  //     ]
  //   },
  // }

  re = RegExp(
    /^(?:(?<protocol>\w+):\/{2})?(?<domain>\/?[^\/\s\?]+)(?:\/(?<paths>[^\?]+))?\/?(?:\?(?<args>.+))?$/
  )
  
  matches = url.match(re);

  parsers = {
    "protocol":parse_protocol,
    "domain":parse_domain,
    "paths":parse_paths,
    "args":parse_args,
  }

  components = {
	  "protocol":null,
	  "domain":null,
	  "paths":null,
	  "args":null,
  }

  if (matches){
    for (id in matches.groups){
      key = id;
      value = matches.groups[id];
      if (parsers[key]){
        value = parsers[key](value);
      }
      
      components[key] = value;
    }
    return components;
  } else{
    return null;
  }

}
